name = "BilevelJuMP"
uuid = "485130c0-026e-11ea-0f1a-6992cd14145c"
authors = ["Joaquim Garcia <joaquimgarcia@psr-inc.com>"]
version = "0.1.0"

[deps]
Dualization = "191a621a-6537-11e9-281d-650236a99e60"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[compat]
Dualization = "~0.2.1"
JuMP = "~0.20.0"
MathOptInterface = "~0.9.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
MathOptFormat = "f4570300-c277-12e8-125c-4912f86ce65d"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"

[targets]
test = ["Test", "Gurobi", "Cbc", "GLPK", "MathOptFormat", "Ipopt"]
