[deps]
BilevelJuMP = "485130c0-026e-11ea-0f1a-6992cd14145c"
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
MibS_jll = "118347d2-e127-56b9-9933-6abf9cc1adc1"
QuadraticToBinary = "014a38d5-7acb-4e20-b6c0-4fe5c2344fd1"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SCIP = "82193955-e24f-5292-bf16-6f2c5261a85f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Documenter = "~0.26"
HiGHS = "=1.5.1"
Ipopt = "=1.0.2"
MibS_jll = "=1.1.3"
QuadraticToBinary = "=0.4.0"
SCIP = "=0.11.12"
